name: Build_and_Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  # TODO: Quick run of just tests
  # test:
  #   name: Cargo Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Install Rust toolchain
  #       uses: dtolnay/rust-toolchain@stable

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-gnu, x86_64-unknown-linux-gnu

      - name: Install cross-compilation dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64

      - name: Build
        run: cargo build --release --target x86_64-pc-windows-gnu --target x86_64-unknown-linux-gnu

      - name: Upload Windows
        uses: actions/upload-artifact@v4
        with:
          name: modulate-comms-win
          path: target/x86_64-pc-windows-gnu/release/modulate-comms.exe

      - name: Upload Linux
        uses: actions/upload-artifact@v4
        with:
          name: modulate-comms-linux
          path: target/release/modulate-comms.exe
