name: Build Executable

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-gnu

      - name: Install cross-compilation dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64

      - name: Build for Windows
        run: cargo build --release --target x86_64-pc-windows-gnu

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: modulate-comms
          path: target/x86_64-pc-windows-gnu/release/modulate-comms.exe
